### ISSUE TITLE
Problem during instalation

### ISSUE THREAD

**Issue by hhkaos** [Esri/node-arcgis#66]
Hi Nick!

I had one problem trying to install de module:
```
node-arcgis-test npm install arcgis
node-arcgis-test@1.0.0 /Users/hhkaos/workspace/node-arcgis-test
└── (empty)

npm WARN EPACKAGEJSON node-arcgis-test@1.0.0 No description
npm WARN EPACKAGEJSON node-arcgis-test@1.0.0 No repository field.
npm ERR! code 1
```
After 10 minutes I noticed that it was because of my npm version, I fixed it just running:
```
node-arcgis-test sudo npm -g install npm@latest
```

Maybe a quickfixes or faq could me useful for beginners, what do you think?

**Comment by hhkaos** [comment]
Noob question... ^_^''.

Now I'm not sure what's happening, but all the dependencies (core-utils-js, dom-serializer, etc) are not been installed:
![screenshot 2016-03-18 08 55 34](https://cloud.githubusercontent.com/assets/826965/13871986/3f74325e-ece7-11e5-8ea9-0af595c1b7fb.png)

Is this the reason causing the problem?

**Comment by ecaldwell** [comment]
You could try `npm install` from the directory with `package.json` to see if it gets any missing dependencies.

**Comment by hhkaos** [comment]
It runs normally :(
```
arc-notifier git:(master) ✗ npm install
arc-notifier git:(master) ✗
```

**Comment by nikolaswise** [comment]
@hhkaos node-arcgis v1.0.0 is super borked, do to 1.0.0 vs 1.0.0-beta.1 craziness. Will publish a v1.0.1  today, since I have patches that came from Dev Summit anyhoo

**Comment by jgravois** [comment]
> @hhkaos: all the dependencies (core-utils-js, dom-serializer, etc) are not been installed:

this node module only has two dependencies of its own ([isomorphic-fetch and sanitize-html](https://github.com/Esri/node-arcgis/blob/master/package.json#L11-L12)).  why were you expecting `core-utils-js` or `dom-serializer` to be installed?

either way, as @nikolaswise said, if you use `npm install arcgis@1.0.0-beta.1` (until we publish 1.0.1), you'll be fine.

**Comment by hhkaos** [comment]
Great guys, running ```npm install arcgis@1.0.0-beta.1``` fixed my problem :).

John I was expecting those modules to be installed because I made a "hello world" example into an empty folder just installing the *node-arcgis* and I thought those modules were installed... but probably I was confused hehe.

Now everything is working,thx!

**Comment by nikolaswise** [comment]
Awesome!
