### ISSUE TITLE
'npm test' just lints

### ISSUE THREAD

**Issue by jgravois** [Esri/node-arcgis#69]
as of [`4e44533`](https://github.com/Esri/node-arcgis/blob/4e4453371f56f141199252714cb0f3f92d10391b/package.json#L74), we aren't running faucet tests anymore.

am i correct in assuming that this is because they need to be tweaked to show green again? if so, maybe we should do that before we release.

**Comment by jgravois** [comment]
scratch that, i think we should definitely tackle this before releasing `1.0.1`

**Comment by nikolaswise** [comment]
@jgravois I've been thinking a lot about how to run tests for the project - I've read a bit that suggests that the role of a project like this is solely to make requests, so one should only test that the proper requests are being made. This simplifies a lot! Keeps code discreet and modular, and auth doesn't matter at all.

**Comment by jgravois** [comment]
i don't know a ton about designing tests, but i agree that this project can and should assume that ArcGIS Online and Portal will respond predictably to appropriately formed requests.

the only other thing that would be appropriate to validate would be any post-processing that's done prior to passing along responses.

**Comment by nikolaswise** [comment]
We could break out the post-processing into their own functions, and feed it dummy data with the expectation it will make `foo` call and `bar` transformation.

**Comment by jgravois** [comment]
fixed by #72
