### ISSUE TITLE
Methods only works with public items?

### ISSUE THREAD

**Issue by hhkaos** [Esri/node-arcgis#70]
I'm trying to access to this [private layer](http://admonlocal.maps.arcgis.com/home/item.html?id=f0ff49a98150486da8cd6b227ca5010d) and it returns ```undefined```, but it doesn't return the promise. I get the token using the administrator account of the organisation, is this the way it should work?. 

When I access to a public item [like this](http://admonlocal.maps.arcgis.com/home/item.html?id=3e8d6de25030466dadc98c7bd7502fb6) it works fine :).

I'm just trying to make an script to know if a feature service is public or not, this is the way to do that right?.

The code I'm using:
```
arcgis.layer('3e8d6de25030466dadc98c7bd7502fb6')
    .then(function (item) {
      console.log('item = ', item);
    });
```
Best Regards,
Raul

**Comment by hhkaos** [comment]
mmmm I'm trying in Portal services and it seem to be working... hehe, I'll check it again

**Comment by nikolaswise** [comment]
Keep us updated!
