### ISSUE TITLE
changelog out of sync with releases & npm

### ISSUE THREAD

**Issue by ungoldman** [Esri/node-arcgis#71]
https://github.com/Esri/node-arcgis/releases -> v1.0.0-beta.1
https://www.npmjs.com/package/arcgis -> v1.0.0-beta.1
https://github.com/Esri/node-arcgis/blob/master/CHANGELOG.md -> v1.0.0-beta.1, v1.0.1 (skipped 1.0.0?)

**Comment by jgravois** [comment]
we botched the release of `1.0.0` so we deprecated it on npm
we also got ahead of ourselves mentioning 1.0.1 in the changelog.  we'll tag that release as soon as we get real tests passing #69

**Comment by nikolaswise** [comment]
1.0.1 is out with basic linting tests - working on more involved tests for the FUTURE!!!!
