### ISSUE TITLE
deploy subfolder to gh-pages

### ISSUE THREAD

**Issue by jgravois** [Esri/node-arcgis#76]
i can't even find the bash script i saw you were using the other day to push to gh-pages, but i think the approach below is simpler (and will avoid including tests, source and other extraneous stuff)

https://gist.github.com/cobyism/4730490

if it'd be helpful for me to PR with a new npm script, just say the word.

**Comment by nikolaswise** [comment]
Keeping built files in version control feels more weird to me. 

The script is in #77! Totally forgot to PR that sucker. It's a little bit of gymnastics, but it keeps the master branch clean and free of generated files.

**Comment by jgravois** [comment]
> it keeps the master branch clean and free of generated files.

yeah, i definitely wasn't suggesting we start pushing `doc-built` into version control in `master`.  inversely, with the script you're using now, it seems weird to me to push stuff like `/lib/` into the `gh-pages` branch.

**Comment by nikolaswise** [comment]
Oh word, so git force add the subtree and push THAT. Good idea.

**Comment by nikolaswise** [comment]
@jgravois updated #77 to do this.
