### ISSUE TITLE
search method expects 'queryString', doc lists 'query'

### ISSUE THREAD

**Issue by jgravois** [Esri/node-arcgis#88]
code: [`queryString`](https://github.com/Esri/node-arcgis/blob/ac8f3e0d31a53a49435a2c455608cd4342a6dbaf/lib/index.js#L14)

doc: [`query`](http://esri.github.io/node-arcgis/#search)

i'm happy to just update the doc, but 'queryString` feels like a clumsy param name to me.

**Comment by jgravois** [comment]
8e0eb62

**Comment by YmerejRedienhcs** [comment]
Thank you.  As a naive user, reading and following the docs, I got bit by this just today.

**Comment by jgravois** [comment]
sorry.  i just tagged `v.1.0.2` and updated the live doc.
