### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by itrew** [Esri/node-arcgis#91]
Was just wondering if there are plans to continue this project in the future.

**Comment by jgravois** [comment]
hi @itrew! we have tackled (and later orphaned) many different low-level OSS node/vanilla JS projects over the years. i'm sad to admit that 'node-arcgis' has joined their illustrious ranks.

that said, very recently we picked up the discussion in https://github.com/Esri/geoservices-js/issues/91 internally and i expect to be sharing more substantive news on that front shortly.

**Comment by itrew** [comment]
@jgravois sad to hear that this is going to be abandoned, but that's the nature of the beast.

Some sort of library that mimics the new Python API in terms of functionality would be really nice to have on the JS side of things. Ideally both server side and in the browser.

**Comment by jgravois** [comment]
today we've open sourced a brand new project usable in both Node.js and modern browsers. :tada:

[`arcgis-rest-js`](https://github.com/Esri/arcgis-rest-js) currently supports making both anonymous and authenticated requests to ArcGIS Online and Enterprise and includes wrappers for geocoding and interacting with ArcGIS Online/Portal items. the microservice architecture will allow developers to install and consume *only* what they need.

You can check out our open issues to see discussions pertaining to the design of upcoming packages. The project has already seen contributions from our PDX and Washington DC R&D labs and Professional Services and will be consumed in https://developers.arcgis.com and https://hub.arcgis.com. 

we hope to broaden the collaboration circle with all our great customers, so if you have questions, comments or concerns, **please** reach out and help us flesh out the doc.

[issues](https://github.com/Esri/arcgis-rest-js/issues)
[FAQ](https://github.com/Esri/arcgis-rest-js#frequently-asked-questions)

npm packages will be landing in the [`@esri`](https://www.npmjs.com/org/esri) namespace shortly.
