### ISSUE TITLE
Add Deprecation Notice to Documentation pages

### ISSUE THREAD

**Issue by gavinr** [Esri/node-arcgis#93]
If someone goes directly [there](http://esri.github.io/node-arcgis/) they won't see this note: 

https://github.com/Esri/node-arcgis/commit/8b7796c6fa66cf7dba0735a9a58505a700ac43be#commitcomment-29724642

**Comment by jgravois** [comment]
https://github.com/Esri/node-arcgis/blob/ab62e06688836e0118ffb3d43ec6b62ef9c2a87a/doc/_layout.html#L33-L36
